CREATE DATABASE SoftUni
USE SoftUni

CREATE TABLE Towns(
Id INT IDENTITY,
[Name] VARCHAR(50) NOT NULL
);

CREATE TABLE Addresses(
Id INT IDENTITY,
AddressText VARCHAR(50),
TownId INT
);

CREATE TABLE Departments(
Id INT IDENTITY,
[Name] VARCHAR(50) NOT NULL
);

CREATE TABLE Employees(
Id INT IDENTITY,
FirstName VARCHAR(50) ,
MiddleName VARCHAR(50),
LastName VARCHAR(50) ,
JobTitle VARCHAR(50),
DepartmentId INT,
HireDate DATE,
Salary DECIMAL(15,2),
AddressId INT
);

ALTER TABLE Towns
ADD CONSTRAINT PK_TownsId PRIMARY KEY(Id)
ALTER TABLE Addresses
ADD CONSTRAINT PK_AddressesId PRIMARY KEY(Id)
ALTER TABLE Addresses
ADD CONSTRAINT FK_AddressesFK 
FOREIGN KEY (Id) REFERENCES Towns(Id);
--USE SoftUni
--ALTER TABLE Addresses
--DROP CONSTRAINT FK_AddressesFK
ALTER TABLE Departments
ADD CONSTRAINT PK_DepartmentsId PRIMARY KEY(Id)
ALTER TABLE Employees
ADD CONSTRAINT PK_EmployeeId PRIMARY KEY(Id)
ALTER TABLE Employees
ADD CONSTRAINT FK_EmployeeDepartmentId
FOREIGN KEY(Id) REFERENCES Departments(Id)
ALTER TABLE Employees
ADD CONSTRAINT FK_EmployeeAddressId
FOREIGN KEY(Id) REFERENCES Addresses(Id)